steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/food-segmentation:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/food-segmentation:latest'
      - '.'
    
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/food-segmentation:$COMMIT_SHA'
  
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/food-segmentation:latest'
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'food-segmentation'
      - '--image'
      - 'gcr.io/$PROJECT_ID/food-segmentation:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '8Gi'
      - '--cpu'
      - '4'
      - '--timeout'
      - '900'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'FLASK_ENV=production'

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/food-segmentation:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/food-segmentation:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
  logging: CLOUD_LOGGING_ONLY
